source "https://rubygems.org"

ruby "~> 3.3"

gem "sinatra", "~> 4.1"
gem "puma", "~> 6.5"
gem "mysql2", "~> 0.5.6"
gem "rackup", "~> 2.2"

group :test do
  gem "minitest", "~> 5.25"
  gem "rake", "~> 13.2"
end
